#!/usr/bin/env bash

# Script to connect to the server using a private key

# Define the server IP address
SERVER_IP="34.229.69.115"

# Use ssh with single-character flags to connect to the server
ssh -i ~/.ssh/school ubuntu@$SERVER_IP
